# Welcome to Jekyll!


# In addition to these settings, there is a file _data/tokens-template.yml
# that you'll want to customize for your site. It's named 'tokens' because
# that was it's original purpose, but because tokens.yml is .gitexcluded, it's
# a good place to store your site-specific data that you'd rather not have
# forked or cloned. Of course, that means you'd want to back it up elsewhere.

# Also, for your post bylines, add author info for yourself in `_data/authors.yml`.
# (Using that method instead of site.owner, in case your posts get cloned with your repo.)

# Site settings
title: LOCUS
description: 享受著設計與程式間交雜的日子

owner:
  name: Locus Today # or company name
  email: yu.locus@gmail.com
  url: http://locus.today
first_published: 2016 # if migrating another site, the year of your first publish
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://locus.today" # the base hostname & protocol for your site

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: 哈囉，我叫游宜衡! 
  text: 2013/8 ~ 到現在<br />在AtticTV Pte Ltd擔任Android Leader<br /><br />回想剛進入AtticTV，我還是個Android開發只學三個多月就勇敢跑來面試的小菜鳥。<br />在神人級的技術長帶領下，慢慢學習到許多程式開發上的技巧，以及創業相關的知識。<br />在新創公司工作的風格，就是不斷地挑戰新事物，嘗試更多創新的思維與觀點，<br />這不僅讓我有更多程式實作經驗的累積，也增強了英文閱讀文件的能力。<br />相信未來我將會更努力不斷地精進自己，嘗試開發出更多良好使用體驗的APP。
# - title for your blog's featured posts
features-title: 工作筆記
# - displayed at the bottom
closing-head: 順便下載玩玩看我的作品吧！
closing-para: 最新力作! GotchaIV - IV Calculator for Pokemon GO
closing-cta: "http://play.google.com/store/search?q=pub:Yu Locus"

# on all pages (and the first three you list display with greeting, if included)
social:
  github: https://github.com/yulocus
  facebook-official: https://www.facebook.com/locus.yu.9
  email: /contact/
  #twitter:
  #linkedin-square: 
  #google-plus-square: 
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here. (I didn't spend time dealing with spaces
# and full paths of the various OSes in compose.rb. For my Windows
# environment, I just put a subl.cmd file in my PATH that points to the full
# path to Sublime's subl.exe.) Also, put your most common post extension.
compose:
  editor: subl
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: none

# expecting more works? mark your list as in-progress
works_in_progress: no

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []
